# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "c1NMUVBFkF+g3calzCn2iuPgjHQfydQhGJV/13jyro3tN4KUHdsWnWg7SdKdAHV6W8M7PzYsY4in3XWzqLQUJ6TVbpZPoqTy5Z/muPsWnCsPUFDzbWJZ5IHYvAyergCbb5Xf+gJuBH7xEckTo4E0e/dGbC8DB2jRpWDwsKTB5xCzNfIl8gavbx+iKXXoNXry6AQXIVddCvMFQwzpxo90gtExW0fnXv2ENDmyU/9aQbMYHRv4LLOVnsN873qtdbBYGVqc1tRyuhni6zxUFKdn/wPGb/+qnHJY26aWgAk1TWDV8d5Dr+qrOKo8sxMYYhS4VC1sVokk9DbDWeBICoMrT6A11t7YObH/b/mtWRJ5VZzK+RmATCRYL2+oPoGfaZfH6ynICwIYvFVgdg5vT2+tPTchqf9kHhwge4Z9h9yxHrjKCDjRD4CoawX7y479d4oIVDBjBUtVEmsuyRUT3H/vZRkZPUJAEFVPvQJYSvE3akzX4jvuBe1lIpTqZmOf3pKnJiEboqCmYmym+0+cqjIZNYrBrsjXDXPHG2Si2XwLsrdW8k7ehZbT5AjWzkIpWOW8EdYdn/Svf/W9cBYfDRVcXJX471lde/BfBItQ7F6BeetXkgbQGPcYAJKD9sa85Wy2s81zYCCElbLdIuRc3nOPgWg7+ho+ZgAyqBEB01TvDCg="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
